version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:13.5 
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.20
    volumes:
      - ./web:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.10
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:
      - REDIS_HOST=queue
      - REDIS_PORT=6379
      - REDIS_FILA=0
      - DB_HOST=db
      - DB_USER=postgres
      - DB_NAME=batatinha_sender
  queue:
    image: redis:6.2
    networks:
      - fila
  worker:
    build: worker
    volumes:
    #worker
      - ./worker:/worker
    working_dir: /worker
    command: ./worker.py
    networks:
      - fila
    depends_on:
      - queue
    
